export const MARKET={x:-3,z:4,name:'Banca do vale'} as const;
export const GOODS=[
  {id:'apple',name:'Maçã',kind:'food',price:2,relief:20,joy:8},
  {id:'bread',name:'Pão',kind:'food',price:3,relief:40,joy:0},
  {id:'water',name:'Água',kind:'drink',price:1,relief:40,joy:0},
  {id:'juice',name:'Suco',kind:'drink',price:3,relief:20,joy:10},
  {id:'pear',name:'Pera',kind:'food',price:2,relief:9,joy:2},
  {id:'plum',name:'Ameixa',kind:'food',price:2,relief:7,joy:2},
  {id:'grapes',name:'Uvas',kind:'food',price:3,relief:8,joy:3},
  {id:'banana',name:'Banana',kind:'food',price:3,relief:10,joy:2},
  {id:'orange',name:'Laranja',kind:'food',price:2,relief:7,joy:2},
  {id:'peach',name:'Pêssego',kind:'food',price:3,relief:8,joy:3},
  {id:'fig',name:'Figo',kind:'food',price:3,relief:7,joy:2},
  {id:'berries',name:'Frutas vermelhas',kind:'food',price:4,relief:6,joy:4},
  {id:'carrot',name:'Cenoura',kind:'food',price:1,relief:5,joy:0},
  {id:'tomato',name:'Tomate',kind:'food',price:1,relief:4,joy:0},
  {id:'corn',name:'Milho cozido',kind:'food',price:3,relief:10,joy:1},
  {id:'potato',name:'Batata assada',kind:'food',price:4,relief:12,joy:1},
  {id:'pumpkin',name:'Abóbora assada',kind:'food',price:4,relief:11,joy:1},
  {id:'soup',name:'Sopa de legumes',kind:'food',price:5,relief:12,joy:2},
  {id:'salad',name:'Salada',kind:'food',price:3,relief:7,joy:1},
  {id:'cheese',name:'Queijo',kind:'food',price:5,relief:10,joy:2},
  {id:'egg',name:'Ovo cozido',kind:'food',price:3,relief:9,joy:1},
  {id:'porridge',name:'Mingau',kind:'food',price:4,relief:11,joy:2},
  {id:'rice',name:'Arroz',kind:'food',price:3,relief:10,joy:0},
  {id:'beans',name:'Feijão',kind:'food',price:4,relief:11,joy:0},
  {id:'cracker',name:'Biscoito salgado',kind:'food',price:2,relief:5,joy:1},
  {id:'honeycake',name:'Bolo de mel',kind:'food',price:7,relief:9,joy:4},
  {id:'nuts',name:'Castanhas',kind:'food',price:5,relief:9,joy:2},
  {id:'herbaltea',name:'Chá de ervas',kind:'drink',price:3,relief:7,joy:2},
  {id:'minttea',name:'Chá de hortelã',kind:'drink',price:3,relief:7,joy:2},
  {id:'chamomile',name:'Chá de camomila',kind:'drink',price:3,relief:7,joy:2},
  {id:'lemontea',name:'Chá de limão',kind:'drink',price:3,relief:7,joy:2},
  {id:'berrytea',name:'Chá de frutas',kind:'drink',price:4,relief:7,joy:3},
  {id:'lemonade',name:'Limonada',kind:'drink',price:4,relief:10,joy:3},
  {id:'limewater',name:'Água com limão',kind:'drink',price:2,relief:9,joy:1},
  {id:'orangeade',name:'Refresco de laranja',kind:'drink',price:4,relief:9,joy:3},
  {id:'grapejuice',name:'Suco de uva',kind:'drink',price:5,relief:10,joy:4},
  {id:'pearjuice',name:'Suco de pera',kind:'drink',price:5,relief:10,joy:4},
  {id:'applejuice',name:'Suco de maçã',kind:'drink',price:5,relief:10,joy:4},
  {id:'plumjuice',name:'Suco de ameixa',kind:'drink',price:5,relief:9,joy:4},
  {id:'berryjuice',name:'Suco de frutas vermelhas',kind:'drink',price:6,relief:9,joy:4},
  {id:'coconutwater',name:'Água de coco',kind:'drink',price:5,relief:12,joy:2},
  {id:'springwater',name:'Água da nascente',kind:'drink',price:3,relief:12,joy:1},
  {id:'warmmilk',name:'Leite morno',kind:'drink',price:4,relief:8,joy:2},
  {id:'coldmilk',name:'Leite fresco',kind:'drink',price:4,relief:9,joy:2},
  {id:'honeywater',name:'Água com mel',kind:'drink',price:5,relief:8,joy:4},
  {id:'gingertea',name:'Chá de gengibre',kind:'drink',price:4,relief:8,joy:2},
  {id:'cinnamontea',name:'Chá de canela',kind:'drink',price:4,relief:8,joy:3},
  {id:'melonwater',name:'Refresco de melão',kind:'drink',price:4,relief:9,joy:3},
  {id:'flowertea',name:'Chá de flores',kind:'drink',price:5,relief:8,joy:3},
  {id:'spiceddrink',name:'Bebida de especiarias',kind:'drink',price:6,relief:8,joy:4},
] as const;
export type GoodId=typeof GOODS[number]['id'];
export function goodById(value:unknown){return GOODS.find(good=>good.id===value);}
