export type FaceExpression='neutral'|'happy'|'sad'|'angry'|'surprised'|'worried';
export type EmotionGroup='Afeto'|'Bem-estar'|'Reflexão'|'Vulnerabilidade'|'Conflito';
export type EmotionDefinition={id:string;label:string;group:EmotionGroup;description:string;effect:readonly [pressure:number,warmth:number,valence:number,trust:number,tension:number,expression:FaceExpression]};

/** Feelings are internal; face expressions remain a smaller visual vocabulary. */
export const emotionCatalog:EmotionDefinition[]=[
  {id:'neutral',label:'Neutro',group:'Reflexão',description:'Nada marcou este momento.',effect:[0,0,0,0,0,'neutral']},
  {id:'affection',label:'Carinho',group:'Afeto',description:'Vontade de estar perto e cuidar.',effect:[-2,3,3,2,-2,'happy']},
  {id:'passion',label:'Paixão',group:'Afeto',description:'Atração intensa por alguém.',effect:[1,4,4,1,0,'happy']},
  {id:'love',label:'Amor',group:'Afeto',description:'Vínculo profundo e duradouro.',effect:[-2,4,4,3,-2,'happy']},
  {id:'tenderness',label:'Ternura',group:'Afeto',description:'Delicadeza diante de outra pessoa.',effect:[-2,3,2,2,-2,'happy']},
  {id:'fondness',label:'Afeição',group:'Afeto',description:'Apego leve e constante.',effect:[-1,2,2,1,-1,'happy']},
  {id:'attraction',label:'Atração',group:'Afeto',description:'Interesse afetivo ou romântico.',effect:[1,2,2,0,0,'happy']},
  {id:'desire',label:'Desejo',group:'Afeto',description:'Vontade de se aproximar.',effect:[1,2,2,0,0,'happy']},
  {id:'devotion',label:'Dedicação',group:'Afeto',description:'Disposição firme de apoiar alguém.',effect:[-1,3,2,3,-1,'happy']},
  {id:'gratitude',label:'Gratidão',group:'Afeto',description:'Reconhecimento por algo recebido.',effect:[-2,2,3,2,-2,'happy']},
  {id:'trust',label:'Confiança',group:'Afeto',description:'Segurança ao contar com alguém.',effect:[-1,2,2,3,-2,'happy']},
  {id:'admiration',label:'Admiração',group:'Afeto',description:'Respeito pelo jeito ou ações de alguém.',effect:[-1,2,2,1,-1,'happy']},
  {id:'empathy',label:'Empatia',group:'Afeto',description:'Sentir junto com outra pessoa.',effect:[-1,2,1,1,-1,'sad']},
  {id:'compassion',label:'Compaixão',group:'Afeto',description:'Desejo de ajudar alguém em dificuldade.',effect:[-1,2,1,2,-1,'sad']},
  {id:'protectiveness',label:'Proteção',group:'Afeto',description:'Vontade de manter alguém a salvo.',effect:[0,2,1,1,0,'worried']},
  {id:'belonging',label:'Pertencimento',group:'Afeto',description:'Sentir-se parte da vida de outros.',effect:[-2,2,3,2,-1,'happy']},
  {id:'joy',label:'Alegria',group:'Bem-estar',description:'Bem-estar espontâneo.',effect:[-2,1,3,1,-2,'happy']},
  {id:'excitement',label:'Empolgação',group:'Bem-estar',description:'Energia diante do que vem pela frente.',effect:[0,1,3,0,-1,'happy']},
  {id:'amusement',label:'Diversão',group:'Bem-estar',description:'Graça em uma situação compartilhada.',effect:[-2,1,2,0,-1,'happy']},
  {id:'contentment',label:'Satisfação',group:'Bem-estar',description:'Apreço pelo presente.',effect:[-2,1,2,0,-1,'happy']},
  {id:'serenity',label:'Serenidade',group:'Bem-estar',description:'Calma sem urgência.',effect:[-3,0,2,0,-2,'neutral']},
  {id:'relief',label:'Alívio',group:'Bem-estar',description:'Peso que diminui depois de uma tensão.',effect:[-3,1,2,1,-2,'happy']},
  {id:'hope',label:'Esperança',group:'Bem-estar',description:'Expectativa de algo bom.',effect:[-1,1,2,0,-1,'happy']},
  {id:'pride',label:'Orgulho',group:'Bem-estar',description:'Satisfação pelo que fez ou conquistou.',effect:[-1,0,2,0,0,'happy']},
  {id:'confidence',label:'Autoconfiança',group:'Bem-estar',description:'Certeza nas próprias capacidades.',effect:[-1,0,2,0,-1,'happy']},
  {id:'courage',label:'Coragem',group:'Bem-estar',description:'Disposição de agir apesar do medo.',effect:[0,0,2,0,-1,'neutral']},
  {id:'curiosity',label:'Curiosidade',group:'Reflexão',description:'Interesse por conhecer melhor algo ou alguém.',effect:[0,1,1,0,0,'surprised']},
  {id:'inspiration',label:'Inspiração',group:'Reflexão',description:'Uma ideia que dá vontade de agir.',effect:[-1,0,2,0,0,'happy']},
  {id:'anticipation',label:'Expectativa',group:'Reflexão',description:'Atenção ao que pode acontecer.',effect:[1,0,1,0,0,'surprised']},
  {id:'surprise',label:'Surpresa',group:'Reflexão',description:'Algo inesperado chamou atenção.',effect:[1,0,0,0,0,'surprised']},
  {id:'nostalgia',label:'Nostalgia',group:'Reflexão',description:'Lembrança agridoce de outro momento.',effect:[1,0,0,0,0,'sad']},
  {id:'longing',label:'Saudade',group:'Vulnerabilidade',description:'Falta que alguém faz.',effect:[1,1,-1,0,0,'sad']},
  {id:'embarrassment',label:'Constrangimento',group:'Vulnerabilidade',description:'Desconforto diante de alguém.',effect:[2,0,-1,-1,1,'worried']},
  {id:'insecurity',label:'Insegurança',group:'Vulnerabilidade',description:'Dúvida sobre si ou sobre um vínculo.',effect:[2,0,-2,-1,1,'worried']},
  {id:'fear',label:'Medo',group:'Vulnerabilidade',description:'Receio de perder algo importante.',effect:[3,0,-2,-1,1,'worried']},
  {id:'worry',label:'Preocupação',group:'Vulnerabilidade',description:'Pensamento insistente sobre um risco.',effect:[2,0,-2,-1,1,'worried']},
  {id:'anxiety',label:'Ansiedade',group:'Vulnerabilidade',description:'Tensão pelo que ainda não aconteceu.',effect:[3,0,-2,-1,1,'worried']},
  {id:'sadness',label:'Tristeza',group:'Vulnerabilidade',description:'Dor emocional ou desânimo.',effect:[3,-1,-2,-1,1,'sad']},
  {id:'loneliness',label:'Solidão',group:'Vulnerabilidade',description:'Falta de companhia ou conexão.',effect:[3,0,-2,0,0,'sad']},
  {id:'disappointment',label:'Decepção',group:'Vulnerabilidade',description:'Algo ou alguém não correspondeu.',effect:[3,-1,-2,-2,2,'sad']},
  {id:'guilt',label:'Culpa',group:'Vulnerabilidade',description:'Peso por algo que fez.',effect:[3,0,-2,-1,1,'sad']},
  {id:'shame',label:'Vergonha',group:'Vulnerabilidade',description:'Vontade de esconder uma falha.',effect:[3,0,-2,-1,1,'sad']},
  {id:'regret',label:'Arrependimento',group:'Vulnerabilidade',description:'Desejo de ter agido diferente.',effect:[3,0,-2,-1,1,'sad']},
  {id:'grief',label:'Luto',group:'Vulnerabilidade',description:'Dor profunda por uma perda.',effect:[4,0,-3,0,1,'sad']},
  {id:'frustration',label:'Frustração',group:'Conflito',description:'Obstáculo repetido gerou tensão.',effect:[3,-1,-2,-1,2,'angry']},
  {id:'irritation',label:'Irritação',group:'Conflito',description:'Incômodo pontual com uma atitude.',effect:[2,-1,-1,-1,2,'angry']},
  {id:'anger',label:'Raiva',group:'Conflito',description:'Reação forte a algo injusto ou ofensivo.',effect:[4,-2,-3,-2,3,'angry']},
  {id:'jealousy',label:'Ciúme',group:'Conflito',description:'Medo de perder atenção ou afeto.',effect:[3,-2,-2,-1,3,'angry']},
  {id:'resentment',label:'Ressentimento',group:'Conflito',description:'Mágoa que permanece.',effect:[4,-2,-3,-2,3,'angry']},
  {id:'suspicion',label:'Desconfiança',group:'Conflito',description:'Dúvida sobre intenção ou sinceridade.',effect:[2,-1,-1,-2,2,'worried']},
  {id:'contempt',label:'Desprezo',group:'Conflito',description:'Perda de respeito por alguém.',effect:[2,-3,-2,-3,3,'angry']},
  {id:'betrayal',label:'Traição',group:'Conflito',description:'Sentiu uma quebra importante de confiança.',effect:[4,-4,-3,-4,4,'sad']},
];

export const emotionById=new Map(emotionCatalog.map(emotion=>[emotion.id,emotion]));
